from __future__ import annotations

import math
from copy import deepcopy
from typing import Any, Dict, List


DEFAULT_OBJECTS: List[Dict[str, Any]] = [
    {
        "id": "floor",
        "label": "Room floor",
        "type": "Floor",
        "supertype": "Building Element",
        "position": [0.0, -0.12, 0.0],
        "width": 7.0,
        "height": 0.12,
        "depth": 5.5,
        "angle": 0.0,
        "immobile": True,
        "cause": "plane_detected",
        "shape": "planar",
        "visualKind": "floor",
        "color": "#718096",
    },
    {
        "id": "back_wall",
        "label": "Back wall",
        "type": "Wall",
        "supertype": "Building Element",
        "position": [0.0, 0.0, -2.7],
        "width": 7.0,
        "height": 2.8,
        "depth": 0.12,
        "angle": 0.0,
        "immobile": True,
        "cause": "plane_detected",
        "shape": "planar",
        "visualKind": "wall",
        "color": "#9aa5b1",
    },
    {
        "id": "side_wall",
        "label": "Side wall",
        "type": "Wall",
        "supertype": "Building Element",
        "position": [3.44, 0.0, 0.0],
        "width": 0.12,
        "height": 2.8,
        "depth": 5.5,
        "angle": 0.0,
        "immobile": True,
        "cause": "plane_detected",
        "shape": "planar",
        "visualKind": "wall",
        "color": "#9aa5b1",
    },
    {
        "id": "table",
        "label": "Work table",
        "type": "Table",
        "supertype": "Furniture",
        "position": [0.0, 0.0, -0.3],
        "width": 3.4,
        "height": 0.76,
        "depth": 1.7,
        "angle": 0.0,
        "immobile": True,
        "cause": "user_captured",
        "shape": "cubical",
        "visualKind": "table",
        "color": "#a67d58",
    },
    {
        "id": "laptop",
        "label": "Laptop",
        "type": "Laptop",
        "supertype": "Device",
        "position": [-0.46, 0.77, -0.38],
        "width": 0.92,
        "height": 0.52,
        "depth": 0.58,
        "angle": -0.08,
        "immobile": False,
        "cause": "object_detected",
        "shape": "cubical",
        "visualKind": "laptop",
        "color": "#333b45",
    },
    {
        "id": "mug",
        "label": "Mug",
        "type": "Mug",
        "supertype": "Container",
        "position": [0.72, 0.77, -0.16],
        "width": 0.34,
        "height": 0.4,
        "depth": 0.34,
        "angle": 0.0,
        "immobile": False,
        "cause": "object_detected",
        "shape": "cylindrical",
        "visualKind": "mug",
        "color": "#d28b5c",
    },
    {
        "id": "book",
        "label": "Field notes",
        "type": "Book",
        "supertype": "Document",
        "position": [-1.13, 0.77, 0.31],
        "width": 0.56,
        "height": 0.08,
        "depth": 0.4,
        "angle": 0.2,
        "immobile": False,
        "cause": "object_detected",
        "shape": "cubical",
        "visualKind": "book",
        "color": "#527a73",
    },
    {
        "id": "lamp",
        "label": "Desk lamp",
        "type": "Lamp",
        "supertype": "Device",
        "position": [1.24, 0.77, 0.33],
        "width": 0.5,
        "height": 1.02,
        "depth": 0.5,
        "angle": -0.35,
        "immobile": False,
        "cause": "object_detected",
        "shape": "irregular",
        "visualKind": "lamp",
        "color": "#d7aa4d",
    },
    {
        "id": "storage_bin",
        "label": "Storage bin",
        "type": "Storage bin",
        "supertype": "Container",
        "position": [0.26, 0.77, 0.36],
        "width": 0.76,
        "height": 0.46,
        "depth": 0.62,
        "angle": 0.06,
        "immobile": False,
        "cause": "object_detected",
        "shape": "cubical",
        "visualKind": "bin",
        "color": "#597187",
    },
    {
        "id": "package",
        "label": "Small package",
        "type": "Package",
        "supertype": "Parcel",
        "position": [0.25, 0.82, 0.35],
        "width": 0.3,
        "height": 0.2,
        "depth": 0.24,
        "angle": -0.08,
        "immobile": False,
        "cause": "object_detected",
        "shape": "cubical",
        "visualKind": "package",
        "color": "#c5a06a",
    },
    {
        "id": "observer",
        "label": "Robot observer",
        "type": "Person",
        "supertype": "Creature",
        "position": [0.0, 0.0, 1.12],
        "width": 0.46,
        "height": 1.72,
        "depth": 0.34,
        "angle": math.pi,
        "immobile": False,
        "cause": "self_tracked",
        "shape": "changing",
        "visualKind": "observer",
        "color": "#32b9ca",
    },
]


PRESETS: List[Dict[str, Any]] = [
    {
        "id": "left-of-laptop",
        "label": "What is left of the laptop?",
        "shortLabel": "Left of laptop",
        "description": "Finds movable tabletop objects in the laptop's left sector.",
        "pipeline": "deduce(topology) | filter(id == 'laptop') | pick(left) | filter(supertype != 'Building Element' AND id != 'observer' AND id != 'table')",
        "focusPredicate": "left",
    },
    {
        "id": "on-table",
        "label": "Which objects are on top of the table?",
        "shortLabel": "On the table",
        "description": "Uses SRpy's unilateral connectivity relation for top contact.",
        "pipeline": "deduce(topology connectivity) | filter(id == 'table') | pick(on)",
        "focusPredicate": "on",
    },
    {
        "id": "near-observer",
        "label": "Which objects are near the observer?",
        "shortLabel": "Near observer",
        "description": "Calculates a scene statistic, then evaluates SRpy proximity.",
        "pipeline": "calc(meanHeight = average(objects.height)) | filter(id == 'observer') | pick(near) | filter(immobile == False)",
        "focusPredicate": "near",
    },
    {
        "id": "tangible-observer",
        "label": "Which objects are tangible from the observer?",
        "shortLabel": "Within reach",
        "description": "Enables observer-relative visibility and tangible reach.",
        "pipeline": "deduce(topology visibility) | filter(id == 'observer') | pick(tangible)",
        "focusPredicate": "tangible",
    },
    {
        "id": "inside-bin",
        "label": "What is inside or fitting into the storage bin?",
        "shortLabel": "Inside the bin",
        "description": "Combines assembly topology with size comparability.",
        "pipeline": "deduce(topology comparability) | filter(id == 'storage_bin') | pick(inside OR fitting)",
        "focusPredicate": "inside",
    },
    {
        "id": "largest-object",
        "label": "What is the largest object in the workspace?",
        "shortLabel": "Largest object",
        "description": "Maps volume to litres, sorts descending, and takes the first result.",
        "pipeline": "filter(supertype != 'Building Element' AND id != 'table' AND id != 'observer') | map(volumeLitres = volume * 1000.0) | sort(volumeLitres >) | slice(1)",
        "focusPredicate": "bigger",
    },
    {
        "id": "observer-left-right",
        "label": "What appears left or right of the laptop to the observer?",
        "shortLabel": "Observer left / right",
        "description": "Compares nearby objects in the observer's coordinate frame.",
        "pipeline": "deduce(topology visibility) | filter(id == 'laptop') | pick(seenleft OR seenright) | filter(supertype != 'Building Element' AND id != 'table' AND id != 'observer')",
        "focusPredicate": "seen left",
    },
    {
        "id": "connected-elements",
        "label": "Which building elements are connected or touching?",
        "shortLabel": "Connected elements",
        "description": "Selects room envelope references that meet another building element.",
        "pipeline": "deduce(topology connectivity) | filter(supertype == 'Building Element') | select(meeting)",
        "focusPredicate": "meeting",
    },
]


def default_scene() -> List[Dict[str, Any]]:
    return deepcopy(DEFAULT_OBJECTS)


def presets() -> List[Dict[str, Any]]:
    return deepcopy(PRESETS)
