from __future__ import annotations

import math
from copy import deepcopy
from typing import Any, Dict, List


DEFAULT_OBJECTS: List[Dict[str, Any]] = [
    {
        "id": "floor",
        "label": "Flat floor",
        "type": "Floor",
        "supertype": "Building Element",
        "position": [0.0, -0.12, 0.0],
        "width": 12.6,
        "height": 0.12,
        "depth": 9.2,
        "angle": 0.0,
        "immobile": True,
        "cause": "plane_detected",
        "shape": "planar",
        "visualKind": "floor",
        "color": "#718096",
    },
    {
        "id": "back_wall",
        "label": "Bedroom window wall",
        "type": "Wall",
        "supertype": "Building Element",
        "position": [-4.0, 0.0, -4.54],
        "width": 4.6,
        "height": 1.6,
        "depth": 0.12,
        "angle": 0.0,
        "immobile": True,
        "cause": "plane_detected",
        "shape": "planar",
        "visualKind": "wallWindow",
        "color": "#9aa5b1",
    },
    {
        "id": "side_wall",
        "label": "East exterior wall",
        "type": "Wall",
        "supertype": "Building Element",
        "position": [6.24, 0.0, 0.0],
        "width": 0.12,
        "height": 1.6,
        "depth": 9.2,
        "angle": 0.0,
        "immobile": True,
        "cause": "plane_detected",
        "shape": "planar",
        "visualKind": "wall",
        "color": "#9aa5b1",
    },
    {
        "id": "table",
        "label": "Study work table",
        "type": "Table",
        "supertype": "Furniture",
        "position": [0.25, 0.0, -2.2],
        "width": 2.4,
        "height": 0.76,
        "depth": 1.35,
        "angle": 0.0,
        "immobile": False,
        "cause": "user_captured",
        "shape": "cubical",
        "visualKind": "table",
        "color": "#a67d58",
    },
    {
        "id": "laptop",
        "label": "Laptop",
        "type": "Laptop",
        "supertype": "Device",
        "position": [-0.4, 0.77, -2.28],
        "width": 0.92,
        "height": 0.52,
        "depth": 0.58,
        "angle": -0.08,
        "immobile": False,
        "cause": "object_detected",
        "shape": "cubical",
        "visualKind": "laptop",
        "color": "#333b45",
    },
    {
        "id": "mug",
        "label": "Mug",
        "type": "Mug",
        "supertype": "Container",
        "position": [1.11, 0.77, -1.89],
        "width": 0.34,
        "height": 0.4,
        "depth": 0.34,
        "angle": 0.0,
        "immobile": False,
        "cause": "object_detected",
        "shape": "cylindrical",
        "visualKind": "mug",
        "color": "#d28b5c",
    },
    {
        "id": "book",
        "label": "Field notes",
        "type": "Book",
        "supertype": "Document",
        "position": [-0.58, 0.77, -1.73],
        "width": 0.56,
        "height": 0.08,
        "depth": 0.4,
        "angle": 0.2,
        "immobile": False,
        "cause": "object_detected",
        "shape": "cubical",
        "visualKind": "book",
        "color": "#527a73",
    },
    {
        "id": "lamp",
        "label": "Desk lamp",
        "type": "Lamp",
        "supertype": "Device",
        "position": [1.1, 0.77, -2.62],
        "width": 0.5,
        "height": 1.02,
        "depth": 0.5,
        "angle": -0.35,
        "immobile": False,
        "cause": "object_detected",
        "shape": "irregular",
        "visualKind": "lamp",
        "color": "#d7aa4d",
    },
    {
        "id": "storage_bin",
        "label": "Storage bin",
        "type": "Storage bin",
        "supertype": "Container",
        "position": [0.49, 0.77, -1.91],
        "width": 0.76,
        "height": 0.46,
        "depth": 0.62,
        "angle": 0.06,
        "immobile": False,
        "cause": "object_detected",
        "shape": "cubical",
        "visualKind": "bin",
        "color": "#597187",
    },
    {
        "id": "package",
        "label": "Small package",
        "type": "Package",
        "supertype": "Parcel",
        "position": [0.48, 0.82, -1.9],
        "width": 0.3,
        "height": 0.2,
        "depth": 0.24,
        "angle": -0.08,
        "immobile": False,
        "cause": "object_detected",
        "shape": "cubical",
        "visualKind": "package",
        "color": "#c5a06a",
    },
    {
        "id": "observer",
        "label": "Robot observer",
        "type": "Person",
        "supertype": "Creature",
        "position": [0.0, 0.0, 0.8],
        "width": 0.46,
        "height": 1.72,
        "depth": 0.34,
        "angle": math.pi,
        "immobile": False,
        "cause": "self_tracked",
        "shape": "changing",
        "visualKind": "observer",
        "color": "#32b9ca",
    },
]


def _wall(id: str, label: str, x: float, z: float, width: float, depth: float, kind: str = "wall") -> Dict[str, Any]:
    return {
        "id": id,
        "label": label,
        "type": "Wall",
        "supertype": "Building Element",
        "position": [x, 0.0, z],
        "width": width,
        "height": 1.6,
        "depth": depth,
        "angle": 0.0,
        "immobile": True,
        "cause": "plane_detected",
        "shape": "planar",
        "visualKind": kind,
        "color": "#9aa5b1",
    }


def _furnishing(id: str, label: str, kind: str, x: float, z: float, width: float, height: float, depth: float, color: str, angle: float = 0.0) -> Dict[str, Any]:
    return {
        "id": id,
        "label": label,
        "type": label,
        "supertype": "Furniture",
        "position": [x, 0.0, z],
        "width": width,
        "height": height,
        "depth": depth,
        "angle": angle,
        "immobile": False,
        "cause": "user_captured",
        "shape": "cubical",
        "visualKind": kind,
        "color": color,
    }


# The wall segments deliberately leave 1.4 m openings into the three back rooms.
# They are measured boxes, so the observer can pass through the openings but not a wall.
DEFAULT_OBJECTS.extend([
    _wall("study_window", "Study window wall", 0.25, -4.54, 3.9, 0.12, "wallWindow"),
    _wall("bath_window", "Bathroom window wall", 4.25, -4.54, 4.1, 0.12, "wallWindow"),
    _wall("west_wall", "West exterior wall", -6.24, 0.0, 0.12, 9.2),
    _wall("front_west", "Front wall, west", -3.85, 4.54, 4.9, 0.12),
    _wall("front_east", "Front wall, east", 3.85, 4.54, 4.9, 0.12),
    _wall("bedroom_study_divider", "Bedroom / study partition", -1.7, -2.16, 0.12, 4.76),
    _wall("study_bath_divider", "Study / bath partition", 2.2, -2.16, 0.12, 4.76),
    _wall("bedroom_entry_west", "Bedroom entry, west pier", -5.45, 0.22, 1.7, 0.12),
    _wall("bedroom_entry_east", "Bedroom entry, east pier", -2.45, 0.22, 1.5, 0.12),
    _wall("study_entry_west", "Study entry, west pier", -1.2, 0.22, 1.0, 0.12),
    _wall("study_entry_east", "Study entry, east pier", 1.45, 0.22, 1.5, 0.12),
    _wall("bath_entry_west", "Bathroom entry, west pier", 2.825, 0.22, 1.25, 0.12),
    _wall("bath_entry_east", "Bathroom entry, east pier", 5.575, 0.22, 1.45, 0.12),
    _furnishing("sofa", "Living sofa", "sofa", -4.4, 1.85, 2.35, 0.82, 1.05, "#7394a2"),
    _furnishing("coffee_table", "Coffee table", "coffeeTable", -4.35, 3.2, 1.0, 0.38, 0.66, "#a9805b"),
    _furnishing("television_cabinet", "Television cabinet", "tvCabinet", -5.7, 0.55, 0.7, 0.55, 1.2, "#826a56"),
    _furnishing("living_plant", "Living-room plant", "plant", -5.5, 3.75, 0.55, 1.1, 0.55, "#5e9676"),
    _furnishing("dining_table", "Dining table", "diningTable", 1.55, 2.5, 1.35, 0.73, 1.35, "#b38b65"),
    _furnishing("dining_chair_north", "Dining chair, north", "chair", 1.55, 1.35, 0.58, 0.85, 0.55, "#7c9aaa"),
    _furnishing("dining_chair_south", "Dining chair, south", "chair", 1.55, 3.67, 0.58, 0.85, 0.55, "#7c9aaa", math.pi),
    _furnishing("kitchen_bar", "Kitchen bar", "kitchenBar", 3.15, 2.55, 1.5, 0.9, 0.75, "#b9956e", math.pi / 2),
    _furnishing("fridge", "Refrigerator", "fridge", 5.55, 0.95, 0.85, 1.75, 0.83, "#b9c8ca", math.pi / 2),
    _furnishing("stove", "Stove", "stove", 5.5, 2.1, 0.9, 0.9, 0.7, "#9daab0", math.pi / 2),
    _furnishing("kitchen_sink", "Kitchen sink", "kitchenSink", 5.5, 3.35, 0.9, 0.9, 0.7, "#a8b6b6", math.pi / 2),
    _furnishing("bed", "Double bed", "bed", -4.35, -2.7, 2.15, 0.64, 2.1, "#8ca3aa", math.pi / 2),
    _furnishing("bedside", "Bedside table", "sideTable", -5.65, -1.15, 0.55, 0.55, 0.5, "#9e805f"),
    _furnishing("wardrobe", "Wardrobe", "wardrobe", -2.10, -3.65, 0.8, 1.7, 0.65, "#a58a70", math.pi / 2),
    _furnishing("study_bookcase", "Study bookcase", "bookcase", 1.7, -3.62, 0.65, 1.65, 0.5, "#9e8767"),
    _furnishing("bathtub", "Bathtub", "bathtub", 4.9, -2.65, 1.65, 0.62, 1.35, "#aac7cf"),
    _furnishing("toilet", "Toilet", "toilet", 2.85, -3.55, 0.65, 0.78, 0.72, "#d5dcd9"),
    _furnishing("bath_sink", "Bathroom sink", "bathSink", 5.55, -0.73, 0.7, 0.9, 0.5, "#c7d6d5"),
])


PRESETS: List[Dict[str, Any]] = [
    {
        "id": "left-of-laptop",
        "label": "What is left of the laptop?",
        "shortLabel": "Left of laptop",
        "description": "Finds movable tabletop objects in the laptop's left sector.",
        "pipeline": "deduce(topology) | filter(id == 'laptop') | pick(left) | filter(supertype != 'Furniture' AND supertype != 'Building Element' AND id != 'observer')",
        "focusPredicate": "left",
    },
    {
        "id": "on-table",
        "label": "Which objects are on top of the table?",
        "shortLabel": "On the table",
        "description": "Uses SRpy's unilateral connectivity relation for top contact.",
        "pipeline": "deduce(topology connectivity) | filter(id == 'table') | pick(on)",
        "focusPredicate": "on",
    },
    {
        "id": "near-observer",
        "label": "Which objects are near the observer?",
        "shortLabel": "Near observer",
        "description": "Calculates a scene statistic, then evaluates SRpy proximity across the flat.",
        "pipeline": "calc(meanHeight = average(objects.height)) | filter(id == 'observer') | pick(near) | filter(supertype != 'Building Element' AND id != 'observer')",
        "focusPredicate": "near",
    },
    {
        "id": "tangible-observer",
        "label": "Which objects are tangible from the observer?",
        "shortLabel": "Within reach",
        "description": "Enables observer-relative visibility and tangible reach.",
        "pipeline": "deduce(topology visibility) | filter(id == 'observer') | pick(tangible)",
        "focusPredicate": "tangible",
    },
    {
        "id": "inside-bin",
        "label": "What is inside or fitting into the storage bin?",
        "shortLabel": "Inside the bin",
        "description": "Combines assembly topology with size comparability.",
        "pipeline": "deduce(topology comparability) | filter(id == 'storage_bin') | pick(inside OR fitting)",
        "focusPredicate": "inside",
    },
    {
        "id": "largest-object",
        "label": "What is the largest object in the workspace?",
        "shortLabel": "Largest object",
        "description": "Maps volume to litres, sorts descending, and takes the first result.",
        "pipeline": "filter(supertype != 'Building Element' AND id != 'table' AND id != 'observer') | map(volumeLitres = volume * 1000.0) | sort(volumeLitres >) | slice(1)",
        "focusPredicate": "bigger",
    },
    {
        "id": "observer-left-right",
        "label": "What appears left or right of the laptop to the observer?",
        "shortLabel": "Observer left / right",
        "description": "Compares nearby objects in the observer's coordinate frame.",
        "pipeline": "deduce(topology visibility) | filter(id == 'laptop') | pick(seenleft OR seenright) | filter(supertype != 'Furniture' AND supertype != 'Building Element' AND id != 'observer')",
        "focusPredicate": "seen left",
    },
    {
        "id": "connected-elements",
        "label": "Which building elements are connected or touching?",
        "shortLabel": "Connected elements",
        "description": "Selects flat wall and floor references that meet another building element.",
        "pipeline": "deduce(topology connectivity) | filter(supertype == 'Building Element') | select(meeting)",
        "focusPredicate": "meeting",
    },
]


def default_scene() -> List[Dict[str, Any]]:
    return deepcopy(DEFAULT_OBJECTS)


def presets() -> List[Dict[str, Any]]:
    return deepcopy(PRESETS)
